"""
Email Alert Channel
==================

Sends alerts via email using SMTP.

Usage:
    from src.alerting.channels.email import EmailChannel
    from src.alerting.alert_manager import Alert, AlertSeverity
    
    channel = EmailChannel(
        smtp_host="smtp.gmail.com",
        smtp_port=587,
        username="alerts@example.com",
        password="...",
        from_email="alerts@example.com",
        to_emails=["admin@example.com"]
    )
    
    alert = Alert(
        title="Critical Violation",
        message="Insider trading detected",
        severity=AlertSeverity.CRITICAL,
        source="Node1"
    )
    
    await channel.send(alert)
"""

import asyncio
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List

logger = logging.getLogger(__name__)


class EmailChannel:
    """
    Email alert channel using SMTP.
    
    Sends formatted alert emails to configured recipients.
    """
    
    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        username: str,
        password: str,
        from_email: str,
        to_emails: List[str],
        use_tls: bool = True
    ):
        """
        Initialize email channel.
        
        Args:
            smtp_host: SMTP server hostname
            smtp_port: SMTP server port
            username: SMTP username
            password: SMTP password
            from_email: Sender email address
            to_emails: List of recipient email addresses
            use_tls: Use TLS encryption
        """
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_email = from_email
        self.to_emails = to_emails
        self.use_tls = use_tls
        self.logger = logging.getLogger(self.__class__.__name__)
    
    async def send(self, alert) -> bool:
        """
        Send alert via email.
        
        Args:
            alert: Alert object to send
        
        Returns:
            True if sent successfully
        """
        # Build email message
        msg = self._build_email(alert)
        
        # Send in thread pool (SMTP is synchronous)
        try:
            await asyncio.to_thread(self._send_smtp, msg)
            self.logger.info(f"Alert sent via email: {alert.title}")
            return True
        except Exception as e:
            self.logger.error(f"Error sending email: {e}")
            return False
    
    def _build_email(self, alert) -> MIMEMultipart:
        """Build email message."""
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[{alert.severity.value.upper()}] {alert.title}"
        msg["From"] = self.from_email
        msg["To"] = ", ".join(self.to_emails)
        
        # Plain text version
        text = f"""
JLAW Forensic Analysis Alert
=============================

Title: {alert.title}
Severity: {alert.severity.value.upper()}
Source: {alert.source}
Time: {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}

Message:
{alert.message}

Additional Information:
"""
        
        if alert.metadata:
            for key, value in alert.metadata.items():
                text += f"\n{key}: {value}"
        
        text += "\n\n---\nThis alert was generated by JLAW Forensic Analysis System"
        
        # HTML version
        html = f"""
<html>
  <head></head>
  <body>
    <h2 style="color: {'#ff0000' if alert.severity.value == 'critical' else '#ff9900' if alert.severity.value in ['warning', 'error'] else '#36a64f'};">
      {alert.title}
    </h2>
    <p><strong>Severity:</strong> {alert.severity.value.upper()}</p>
    <p><strong>Source:</strong> {alert.source}</p>
    <p><strong>Time:</strong> {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
    <hr>
    <h3>Message:</h3>
    <p>{alert.message}</p>
"""
        
        if alert.metadata:
            html += "<h3>Additional Information:</h3><ul>"
            for key, value in alert.metadata.items():
                html += f"<li><strong>{key}:</strong> {value}</li>"
            html += "</ul>"
        
        html += """
    <hr>
    <p><em>This alert was generated by JLAW Forensic Analysis System</em></p>
  </body>
</html>
"""
        
        # Attach both versions
        msg.attach(MIMEText(text, "plain"))
        msg.attach(MIMEText(html, "html"))
        
        return msg
    
    def _send_smtp(self, msg: MIMEMultipart):
        """Send email via SMTP (synchronous)."""
        with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
            if self.use_tls:
                server.starttls()
            
            server.login(self.username, self.password)
            server.sendmail(
                self.from_email,
                self.to_emails,
                msg.as_string()
            )
