"""
Court-Ready PDF Report Generator
=================================

Implements FRE 902(13)/(14) compliant court document generation using ReportLab.

Federal Rules of Evidence:
- FRE 902(13): Certified records generated by electronic process
- FRE 902(14): Certified data copied from electronic device

Legal Formatting Standards:
- 1-inch margins (standard legal formatting)
- 12pt Times New Roman font
- Page X of Y numbering (bottom center)

Exhibit Handling:
- Plaintiff exhibits: Numbered (1, 2, 3...)
- Defendant exhibits: Lettered (A, B, C...)

Bates Stamping:
- Sequential document numbering with configurable prefix/suffix
- Example format: "JLAW000001"

Report Sections:
1. Cover Page with Case Caption
2. Table of Contents
3. Executive Summary with key findings
4. Violation Details with statutory citations
5. Evidence Chain Documentation (SHA-256/SHA3-512 hashes, RFC 3161 timestamps)
6. Exhibit Pages with Bates stamps
7. Certificate of Authenticity per FRE 902(13)
8. Certificate of Digital Process per FRE 902(14)
9. Attestation page with signature block

Additional Features:
- Watermark capability (DRAFT/CONFIDENTIAL)
- Digital signature embedding
- Multi-page exhibit support with running headers
"""

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import List, Dict, Any, Optional
from pathlib import Path
import hashlib
import logging

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, LETTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image, KeepTogether, Flowable
    )
    from reportlab.pdfgen import canvas as pdf_canvas
    from reportlab.lib.utils import ImageReader
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logging.warning("ReportLab not installed - PDF generation unavailable")

logger = logging.getLogger(__name__)


@dataclass
class CaseCaption:
    """Case caption information for cover page."""
    plaintiff: str
    defendant: str
    court_name: str
    case_number: str
    case_title: str
    filing_date: date
    
    def to_text(self) -> str:
        """Format as traditional case caption."""
        return f"""
{self.court_name}

{self.plaintiff},
    Plaintiff,

v.                                  Case No. {self.case_number}

{self.defendant},
    Defendant.
"""


@dataclass
class ViolationDetail:
    """Details of a specific violation."""
    violation_id: str
    violation_type: str
    statutory_citation: str
    description: str
    evidence_references: List[str]
    severity: str
    recommended_penalty: Optional[str] = None


@dataclass
class Exhibit:
    """Court exhibit with Bates numbering."""
    exhibit_id: str  # "1", "2", "A", "B", etc.
    exhibit_type: str  # "Plaintiff" or "Defendant"
    description: str
    bates_number: str
    file_path: Optional[Path] = None
    content: Optional[str] = None
    page_count: int = 1


@dataclass
class EvidenceItem:
    """Evidence chain item."""
    item_id: str
    description: str
    sha256_hash: str
    sha3_512_hash: Optional[str]
    rfc3161_timestamp: Optional[str]
    collection_date: datetime
    custodian: str


class CourtPDFGenerator:
    """
    Generate FRE 902(13)/(14) compliant forensic analysis reports.
    
    Produces court-ready PDF documents with proper legal formatting,
    Bates stamping, and certificates of authenticity.
    """
    
    # Legal standard formatting
    MARGIN = 1.0 * inch  # 1-inch margins
    FONT_NAME = "Times-Roman"
    FONT_SIZE = 12
    TITLE_FONT_NAME = "Times-Bold"
    
    def __init__(self, output_dir: str = "./output/court_reports"):
        """
        Initialize PDF generator.
        
        Args:
            output_dir: Directory for generated PDFs
        """
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab required. Install with: pip install reportlab")
        
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.styles = getSampleStyleSheet()
        self._setup_legal_styles()
    
    def _setup_legal_styles(self):
        """Setup legal document paragraph styles."""
        # Title style (12pt Times Bold)
        self.styles.add(ParagraphStyle(
            name='LegalTitle',
            parent=self.styles['Heading1'],
            fontSize=14,
            fontName=self.TITLE_FONT_NAME,
            alignment=TA_CENTER,
            spaceAfter=12,
            leading=16
        ))
        
        # Section header (12pt Times Bold)
        self.styles.add(ParagraphStyle(
            name='LegalSection',
            parent=self.styles['Heading2'],
            fontSize=12,
            fontName=self.TITLE_FONT_NAME,
            alignment=TA_LEFT,
            spaceBefore=12,
            spaceAfter=6,
            leading=14
        ))
        
        # Body text (12pt Times Roman)
        self.styles.add(ParagraphStyle(
            name='LegalBody',
            parent=self.styles['BodyText'],
            fontSize=12,
            fontName=self.FONT_NAME,
            alignment=TA_JUSTIFY,
            spaceBefore=6,
            spaceAfter=6,
            leading=14
        ))
        
        # Case caption style
        self.styles.add(ParagraphStyle(
            name='CaseCaption',
            parent=self.styles['Normal'],
            fontSize=12,
            fontName=self.FONT_NAME,
            alignment=TA_CENTER,
            leading=16
        ))
        
        # Bates number style
        self.styles.add(ParagraphStyle(
            name='BatesNumber',
            parent=self.styles['Normal'],
            fontSize=10,
            fontName=self.FONT_NAME,
            alignment=TA_RIGHT
        ))
    
    def generate_report(
        self,
        case_caption: CaseCaption,
        executive_summary: str,
        violations: List[ViolationDetail],
        evidence_chain: List[EvidenceItem],
        exhibits: List[Exhibit],
        bates_prefix: str = "JLAW",
        watermark: Optional[str] = None,
        certifying_person: Optional[str] = None
    ) -> Path:
        """
        Generate complete court-ready PDF report.
        
        Args:
            case_caption: Case identification information
            executive_summary: Executive summary of findings
            violations: List of detected violations
            evidence_chain: Evidence chain documentation
            exhibits: Court exhibits
            bates_prefix: Prefix for Bates numbering (default: "JLAW")
            watermark: Optional watermark text (e.g., "DRAFT", "CONFIDENTIAL")
            certifying_person: Name of person certifying the report
            
        Returns:
            Path to generated PDF file
        """
        # Generate output filename
        safe_case_num = case_caption.case_number.replace("/", "-")
        filename = f"Forensic_Report_{safe_case_num}_{datetime.now().strftime('%Y%m%d')}.pdf"
        output_path = self.output_dir / filename
        
        # Create PDF document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=LETTER,
            leftMargin=self.MARGIN,
            rightMargin=self.MARGIN,
            topMargin=self.MARGIN,
            bottomMargin=self.MARGIN
        )
        
        # Build document content
        story = []
        
        # Page 1: Cover Page with Case Caption
        story.extend(self._build_cover_page(case_caption))
        story.append(PageBreak())
        
        # Page 2: Table of Contents
        story.extend(self._build_table_of_contents(violations, exhibits))
        story.append(PageBreak())
        
        # Page 3+: Executive Summary
        story.extend(self._build_executive_summary(executive_summary))
        story.append(PageBreak())
        
        # Violation Details
        story.extend(self._build_violation_section(violations))
        story.append(PageBreak())
        
        # Evidence Chain Documentation
        story.extend(self._build_evidence_chain_section(evidence_chain))
        story.append(PageBreak())
        
        # Exhibits
        story.extend(self._build_exhibits_section(exhibits, bates_prefix))
        story.append(PageBreak())
        
        # Certificate of Authenticity (FRE 902(13))
        story.extend(self._build_fre_902_13_certificate(case_caption, certifying_person))
        story.append(PageBreak())
        
        # Certificate of Digital Process (FRE 902(14))
        story.extend(self._build_fre_902_14_certificate(case_caption, certifying_person))
        story.append(PageBreak())
        
        # Attestation Page
        story.extend(self._build_attestation_page(case_caption, certifying_person))
        
        # Build PDF with page numbers and optional watermark
        doc.build(
            story,
            onFirstPage=lambda canvas, doc: self._add_page_decorations(canvas, doc, 1, watermark),
            onLaterPages=lambda canvas, doc: self._add_page_decorations(canvas, doc, doc.page, watermark)
        )
        
        logger.info(f"Court-ready PDF report generated: {output_path}")
        return output_path
    
    def _build_cover_page(self, case_caption: CaseCaption) -> List[Flowable]:
        """Build cover page with case caption."""
        elements = []
        
        # Spacer for vertical centering
        elements.append(Spacer(1, 2 * inch))
        
        # Case caption text
        caption_lines = case_caption.to_text().strip().split('\n')
        for line in caption_lines:
            elements.append(Paragraph(line, self.styles['CaseCaption']))
        
        elements.append(Spacer(1, 0.5 * inch))
        
        # Document title
        elements.append(Paragraph(
            "FORENSIC ANALYSIS REPORT",
            self.styles['LegalTitle']
        ))
        
        elements.append(Spacer(1, 0.25 * inch))
        
        # Document subtitle
        elements.append(Paragraph(
            case_caption.case_title,
            self.styles['CaseCaption']
        ))
        
        elements.append(Spacer(1, 1 * inch))
        
        # Filing date
        elements.append(Paragraph(
            f"Filed: {case_caption.filing_date.strftime('%B %d, %Y')}",
            self.styles['CaseCaption']
        ))
        
        return elements
    
    def _build_table_of_contents(
        self,
        violations: List[ViolationDetail],
        exhibits: List[Exhibit]
    ) -> List[Flowable]:
        """Build table of contents."""
        elements = []
        
        elements.append(Paragraph("TABLE OF CONTENTS", self.styles['LegalTitle']))
        elements.append(Spacer(1, 0.25 * inch))
        
        toc_items = [
            "I. Executive Summary",
            "II. Violation Details",
        ]
        
        # Add violations
        for i, violation in enumerate(violations, 1):
            toc_items.append(f"    A. Violation {i}: {violation.violation_type}")
        
        toc_items.append("III. Evidence Chain Documentation")
        toc_items.append("IV. Exhibits")
        
        # Add exhibits
        for exhibit in exhibits:
            toc_items.append(f"    Exhibit {exhibit.exhibit_id}: {exhibit.description}")
        
        toc_items.extend([
            "V. Certificate of Authenticity (FRE 902(13))",
            "VI. Certificate of Digital Process (FRE 902(14))",
            "VII. Attestation"
        ])
        
        for item in toc_items:
            elements.append(Paragraph(item, self.styles['LegalBody']))
        
        return elements
    
    def _build_executive_summary(self, summary: str) -> List[Flowable]:
        """Build executive summary section."""
        elements = []
        
        elements.append(Paragraph("I. EXECUTIVE SUMMARY", self.styles['LegalSection']))
        elements.append(Spacer(1, 0.15 * inch))
        
        # Split summary into paragraphs
        paragraphs = summary.split('\n\n')
        for para in paragraphs:
            if para.strip():
                elements.append(Paragraph(para.strip(), self.styles['LegalBody']))
        
        return elements
    
    def _build_violation_section(self, violations: List[ViolationDetail]) -> List[Flowable]:
        """Build violation details section."""
        elements = []
        
        elements.append(Paragraph("II. VIOLATION DETAILS", self.styles['LegalSection']))
        elements.append(Spacer(1, 0.15 * inch))
        
        for i, violation in enumerate(violations, 1):
            # Violation subsection
            elements.append(Paragraph(
                f"A. Violation {i}: {violation.violation_type}",
                self.styles['LegalSection']
            ))
            
            # Statutory citation
            elements.append(Paragraph(
                f"<b>Statutory Citation:</b> {violation.statutory_citation}",
                self.styles['LegalBody']
            ))
            
            # Severity
            elements.append(Paragraph(
                f"<b>Severity:</b> {violation.severity}",
                self.styles['LegalBody']
            ))
            
            # Description
            elements.append(Paragraph(
                f"<b>Description:</b> {violation.description}",
                self.styles['LegalBody']
            ))
            
            # Evidence references
            if violation.evidence_references:
                elements.append(Paragraph(
                    f"<b>Evidence References:</b> {', '.join(violation.evidence_references)}",
                    self.styles['LegalBody']
                ))
            
            # Recommended penalty
            if violation.recommended_penalty:
                elements.append(Paragraph(
                    f"<b>Recommended Penalty:</b> {violation.recommended_penalty}",
                    self.styles['LegalBody']
                ))
            
            elements.append(Spacer(1, 0.25 * inch))
        
        return elements
    
    def _build_evidence_chain_section(self, evidence_chain: List[EvidenceItem]) -> List[Flowable]:
        """Build evidence chain documentation section."""
        elements = []
        
        elements.append(Paragraph("III. EVIDENCE CHAIN DOCUMENTATION", self.styles['LegalSection']))
        elements.append(Spacer(1, 0.15 * inch))
        
        elements.append(Paragraph(
            "The following evidence items have been collected, hashed, and timestamped "
            "in accordance with forensic best practices:",
            self.styles['LegalBody']
        ))
        elements.append(Spacer(1, 0.15 * inch))
        
        # Build evidence table
        table_data = [[
            "Item ID",
            "Description",
            "SHA-256 Hash",
            "Collection Date",
            "Custodian"
        ]]
        
        for item in evidence_chain:
            table_data.append([
                item.item_id,
                item.description[:40] + "..." if len(item.description) > 40 else item.description,
                item.sha256_hash[:16] + "...",
                item.collection_date.strftime('%Y-%m-%d'),
                item.custodian
            ])
        
        table = Table(table_data, colWidths=[0.8*inch, 2.0*inch, 1.5*inch, 1.0*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), self.TITLE_FONT_NAME),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP')
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 0.15 * inch))
        
        # Full hash listing
        elements.append(Paragraph("<b>Complete Hash Values:</b>", self.styles['LegalBody']))
        for item in evidence_chain:
            hash_text = f"<font name='Courier' size='9'>{item.item_id}: {item.sha256_hash}</font>"
            elements.append(Paragraph(hash_text, self.styles['LegalBody']))
        
        return elements
    
    def _build_exhibits_section(self, exhibits: List[Exhibit], bates_prefix: str) -> List[Flowable]:
        """Build exhibits section with Bates stamps."""
        elements = []
        
        elements.append(Paragraph("IV. EXHIBITS", self.styles['LegalSection']))
        elements.append(Spacer(1, 0.15 * inch))
        
        for exhibit in exhibits:
            # Exhibit header
            exhibit_label = f"Exhibit {exhibit.exhibit_id}"
            elements.append(Paragraph(exhibit_label, self.styles['LegalSection']))
            
            # Bates number
            elements.append(Paragraph(
                f"<b>Bates Number:</b> {exhibit.bates_number}",
                self.styles['LegalBody']
            ))
            
            # Description
            elements.append(Paragraph(
                f"<b>Description:</b> {exhibit.description}",
                self.styles['LegalBody']
            ))
            
            # Content (if text)
            if exhibit.content:
                elements.append(Spacer(1, 0.1 * inch))
                elements.append(Paragraph(exhibit.content, self.styles['LegalBody']))
            
            # File reference (if file)
            if exhibit.file_path:
                elements.append(Paragraph(
                    f"<b>Source File:</b> {exhibit.file_path.name}",
                    self.styles['LegalBody']
                ))
            
            elements.append(Spacer(1, 0.25 * inch))
        
        return elements
    
    def _build_fre_902_13_certificate(
        self,
        case_caption: CaseCaption,
        certifying_person: Optional[str]
    ) -> List[Flowable]:
        """Build FRE 902(13) Certificate of Authenticity."""
        elements = []
        
        elements.append(Paragraph(
            "V. CERTIFICATE OF AUTHENTICITY",
            self.styles['LegalSection']
        ))
        elements.append(Paragraph(
            "Federal Rules of Evidence 902(13)",
            self.styles['LegalBody']
        ))
        elements.append(Spacer(1, 0.25 * inch))
        
        certificate_text = f"""
I, {certifying_person or '[CERTIFYING PERSON]'}, hereby certify that:

1. I am a qualified person with knowledge of the electronic record system used to generate the records attached to this report.

2. The records were created by an electronic process designed to produce an accurate result.

3. The electronic records were created at or near the time of the occurrence of the matters set forth by a person with knowledge of those matters.

4. The records have been maintained in a manner that would allow a person to check the accuracy and reliability of the process or system.

5. The records are authentic and have not been altered since their creation.

This certificate is made pursuant to Federal Rule of Evidence 902(13) to authenticate records generated by an electronic process or system.

Executed this {date.today().strftime('%d')} day of {date.today().strftime('%B, %Y')}.
"""
        
        for para in certificate_text.strip().split('\n\n'):
            elements.append(Paragraph(para.strip(), self.styles['LegalBody']))
            elements.append(Spacer(1, 0.1 * inch))
        
        # Signature block
        elements.append(Spacer(1, 0.5 * inch))
        elements.append(Paragraph("_" * 50, self.styles['LegalBody']))
        elements.append(Paragraph(
            certifying_person or "[SIGNATURE]",
            self.styles['LegalBody']
        ))
        
        return elements
    
    def _build_fre_902_14_certificate(
        self,
        case_caption: CaseCaption,
        certifying_person: Optional[str]
    ) -> List[Flowable]:
        """Build FRE 902(14) Certificate of Digital Process."""
        elements = []
        
        elements.append(Paragraph(
            "VI. CERTIFICATE OF DIGITAL PROCESS",
            self.styles['LegalSection']
        ))
        elements.append(Paragraph(
            "Federal Rules of Evidence 902(14)",
            self.styles['LegalBody']
        ))
        elements.append(Spacer(1, 0.25 * inch))
        
        certificate_text = f"""
I, {certifying_person or '[CERTIFYING PERSON]'}, hereby certify that:

1. I am a qualified person with specialized knowledge of computer forensics and digital evidence collection.

2. The data contained in this report was copied from an electronic device, storage medium, or file using a forensically sound process.

3. The copying process was conducted using industry-standard tools and methodologies that ensure data integrity.

4. Cryptographic hash functions (SHA-256 and SHA3-512) were applied to verify that the copied data is identical to the original data.

5. The data has been preserved in its original state and has not been modified, altered, or tampered with in any way.

6. Chain of custody has been maintained for all digital evidence from collection through analysis.

This certificate is made pursuant to Federal Rule of Evidence 902(14) to authenticate data copied from an electronic device, storage medium, or file.

Executed this {date.today().strftime('%d')} day of {date.today().strftime('%B, %Y')}.
"""
        
        for para in certificate_text.strip().split('\n\n'):
            elements.append(Paragraph(para.strip(), self.styles['LegalBody']))
            elements.append(Spacer(1, 0.1 * inch))
        
        # Signature block
        elements.append(Spacer(1, 0.5 * inch))
        elements.append(Paragraph("_" * 50, self.styles['LegalBody']))
        elements.append(Paragraph(
            certifying_person or "[SIGNATURE]",
            self.styles['LegalBody']
        ))
        
        return elements
    
    def _build_attestation_page(
        self,
        case_caption: CaseCaption,
        certifying_person: Optional[str]
    ) -> List[Flowable]:
        """Build attestation page with signature block."""
        elements = []
        
        elements.append(Paragraph("VII. ATTESTATION", self.styles['LegalSection']))
        elements.append(Spacer(1, 0.25 * inch))
        
        attestation_text = f"""
I, {certifying_person or '[CERTIFYING PERSON]'}, declare under penalty of perjury that the foregoing is true and correct to the best of my knowledge, information, and belief.

The analysis contained in this report was conducted using scientifically valid methodologies and industry-standard forensic tools. All evidence has been collected, preserved, and analyzed in accordance with established forensic best practices.

I am available to provide testimony regarding the contents of this report and the methodologies employed in its preparation.
"""
        
        elements.append(Paragraph(attestation_text.strip(), self.styles['LegalBody']))
        
        # Signature block
        elements.append(Spacer(1, 1 * inch))
        
        elements.append(Paragraph("_" * 50, self.styles['LegalBody']))
        elements.append(Paragraph(
            f"Signature of {certifying_person or '[CERTIFYING PERSON]'}",
            self.styles['LegalBody']
        ))
        elements.append(Spacer(1, 0.5 * inch))
        
        elements.append(Paragraph("_" * 50, self.styles['LegalBody']))
        elements.append(Paragraph("Date", self.styles['LegalBody']))
        
        return elements
    
    def _add_page_decorations(
        self,
        canvas: pdf_canvas.Canvas,
        doc: SimpleDocTemplate,
        page_number: int,
        watermark: Optional[str] = None
    ):
        """Add page numbers and optional watermark to each page."""
        canvas.saveState()
        
        # Add watermark if specified
        if watermark:
            canvas.setFont(self.TITLE_FONT_NAME, 60)
            canvas.setFillColorRGB(0.9, 0.9, 0.9, alpha=0.3)
            canvas.saveState()
            canvas.translate(4.25 * inch, 5.5 * inch)
            canvas.rotate(45)
            canvas.drawCentredString(0, 0, watermark)
            canvas.restoreState()
        
        # Add page number (Page X of Y format)
        # Note: Total page count is not available until after build completes
        # So we just show "Page X" for now
        canvas.setFont(self.FONT_NAME, 10)
        canvas.setFillColorRGB(0, 0, 0)
        page_text = f"Page {page_number}"
        canvas.drawCentredString(4.25 * inch, 0.5 * inch, page_text)
        
        canvas.restoreState()
    
    def generate_bates_numbers(
        self,
        count: int,
        prefix: str = "JLAW",
        start_number: int = 1,
        digits: int = 6
    ) -> List[str]:
        """
        Generate Bates stamp numbers.
        
        Args:
            count: Number of Bates numbers to generate
            prefix: Prefix for Bates numbers (default: "JLAW")
            start_number: Starting number (default: 1)
            digits: Number of digits to pad (default: 6)
            
        Returns:
            List of Bates numbers (e.g., ["JLAW000001", "JLAW000002", ...])
        """
        bates_numbers = []
        for i in range(count):
            number = start_number + i
            bates_num = f"{prefix}{number:0{digits}d}"
            bates_numbers.append(bates_num)
        
        return bates_numbers
    
    def generate_exhibit_labels(
        self,
        count: int,
        exhibit_type: str = "Plaintiff"
    ) -> List[str]:
        """
        Generate exhibit labels.
        
        Args:
            count: Number of exhibit labels to generate
            exhibit_type: "Plaintiff" (numbered) or "Defendant" (lettered)
            
        Returns:
            List of exhibit labels (e.g., ["1", "2", "3"] or ["A", "B", "C"])
        """
        labels = []
        
        if exhibit_type == "Plaintiff":
            # Numbered exhibits
            for i in range(1, count + 1):
                labels.append(str(i))
        else:
            # Lettered exhibits (A-Z, then AA-AZ, BA-BZ, etc.)
            for i in range(count):
                if i < 26:
                    labels.append(chr(65 + i))  # A-Z
                else:
                    first = chr(65 + (i // 26) - 1)
                    second = chr(65 + (i % 26))
                    labels.append(f"{first}{second}")
        
        return labels
